spring:
  config:
    activate:
      on-profile: prod
  h2:
    console:
      enabled: false
aws:
  dynamodb:
    endpoint: "${AWS_DYNAMODB_ENDPOINT:}"
    seed-enabled: "${DYNAMODB_SEED_ENABLED:false}"
cors:
  allowed-origins: "${CORS_ALLOWED_ORIGINS:}"
