package co.com.yam.funds.api.dto;

import co.com.yam.funds.model.transaction.Transaction;
import co.com.yam.funds.model.transaction.TransactionType;
import io.swagger.v3.oas.annotations.media.Schema;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.UUID;

@Schema(description = "Client transaction generated by subscription or cancellation operations.")
public record TransactionResponse(
        @Schema(description = "Transaction identifier.", example = "00000000-0000-0000-0000-000000000001")
        UUID id,
        @Schema(description = "Client identifier.", example = "client-001")
        String clientId,
        @Schema(description = "Fund identifier.", example = "1")
        String fundId,
        @Schema(description = "Fund display name.", example = "FPV_YAM_PACTUAL_RECAUDADORA")
        String fundName,
        @Schema(description = "Transaction type.", example = "SUBSCRIPTION")
        TransactionType type,
        @Schema(description = "Transaction amount.", example = "75000")
        BigDecimal amount,
        @Schema(description = "Transaction timestamp.", example = "2026-08-11T00:00:00Z", format = "date-time")
        Instant timestamp
) {
    public static TransactionResponse from(Transaction transaction) {
        return new TransactionResponse(
                transaction.getId(),
                transaction.getClientId(),
                transaction.getFundId(),
                transaction.getFundName(),
                transaction.getType(),
                transaction.getAmount(),
                transaction.getTimestamp()
        );
    }
}
