dependencies {
    implementation project(':model')
    implementation 'org.springframework:spring-context'
    implementation 'software.amazon.awssdk:dynamodb-enhanced'
    implementation 'org.reactivecommons.utils:object-mapper-api:0.1.0'
    testImplementation 'org.reactivecommons.utils:object-mapper:0.1.0'
    testImplementation platform('org.testcontainers:testcontainers-bom:1.21.4')
    testImplementation 'org.testcontainers:junit-jupiter'
    testImplementation 'org.testcontainers:testcontainers'
}
