apply plugin: 'org.springframework.boot'

dependencies {
	implementation 'org.reactivecommons.utils:object-mapper:0.1.0'
	implementation project(':dynamo-db')
	implementation project(':metrics')
	implementation 'software.amazon.awssdk:sts'
	testImplementation 'tools.jackson.core:jackson-databind'
    testImplementation 'tools.jackson.core:jackson-databind:3.0.4'
    implementation project(':model')
    implementation project(':usecase')
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    runtimeOnly('org.springframework.boot:spring-boot-devtools')
    testImplementation 'com.tngtech.archunit:archunit:1.4.1'
}

tasks.register('explodedJar', Copy) {
    with jar
    into layout.buildDirectory.dir("exploded")
}

jar {
    // To disable the *-plain.jar
    enabled = false
}

bootJar {
    // Sets output jar name
    archiveFileName = "${project.getParent().getName()}.${archiveExtension.get()}"
}